export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const ITINERARY_SAVE_SUCCESS = "ITINERARY_SAVE_SUCCESS";
export const ITINERARY_SAVE_FAILURE = "ITINERARY_SAVE_FAILURE";
export const ITINERARY_DETAIL = "ITINERARY_DETAIL";

export const ITINERARY_PLAN_DETAILS = "ITINERARY_PLAN_DETAILS";
